---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks
- Trabajo:
    - Moodle:
        - icon: https://cdn.icon-icons.com/icons2/2415/PNG/512/moodle_original_logo_icon_146420.png
          href: https://frontal.ies-sabadell.cat/cicles-moodle/login/index.php
    - Gmail:
        - icon: gmail.png
          href: https://mail.google.com/mail/u/0/?pli=1#inbox
    - Drive:
        - abbr: GH
          icon: https://upload.wikimedia.org/wikipedia/commons/d/da/Google_Drive_logo.png
          href: https://drive.google.com/drive/u/0/my-drive

- Síntesis:
    - Kodular:
        - icon: https://upload.wikimedia.org/wikipedia/commons/6/6d/Kodular_Logo.png
          href: https://drive.google.com/drive/folders/1tqpeymREdbkR6Fd0_CHTjQlfsgeMLFdG?usp=sharing
    - RetroJoc:
        - icon: https://cdn.icon-icons.com/icons2/1381/PNG/512/retropie_93897.png
          href: https://drive.google.com/drive/folders/1GLMksE3GEli4rmjdV3df1k43tKzMt2e4?usp=sharing
    - IoT:
        - icon: arduino.png
          href: https://drive.google.com/drive/folders/1n_0X-wcO0RioHIfnQRaOtamo2xADBlw5?usp=sharing

- Documentación:
    - Doc 1:
        - icon: youtube.png
          href: https://youtube.com
    - Doc 2:
        - icon: youtube.png
          href: https://youtube.com
    - Doc 3:
        - icon: youtube.png
          href: https://youtube.com
