---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Ficheros y Backups:

    - Nextcloud:
        icon: nextcloud.png
        href: https://10.1.6.130
        description: Almacenamiento general de ficheros

    - Transmission:
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Transmission_Icon.svg/1200px-Transmission_Icon.svg.png
        href: http://10.1.6.130:9091
        description: Gestion y descarga de torrents

    - Opengist:
        icon: opengist.png
        href: http://10.1.6.130:6157
        description: Compartición de codigo sencilla y ràpida

    - Immich:
        icon: immich.png
        href: http://10.1.6.130:2283
        description: Compartición y almacenamiento de Imagenes

- Entretenimiento:

    - Plex:
        icon: plex.png
        href: http://10.1.6.130:32400
        description: Streaming de peliculas y series

    - Jellyfin:
        icon: jellyfin.png
        href: http://10.1.6.130:8096
        description: Streaming de peliculas y series

    - Overseerr:
        icon: overseerr.png
        href: http://10.1.6.130:5055
        description: Listado y solicitud de peliculas y series

    - Kavita:
        icon: kavita.png
        href: http://10.1.6.130:5471
        description: Lector de comics y manga

    - Audiobookshelf:
        icon: audiobookshelf.png
        href: http://10.1.6.130:13378
        description: Bibilioteca digital de Audiolibros

    - Formula 1:
        icon: https://burnoutf1.com/img/F1/iconos/logo.png
        href: https://burnoutf1.com/
        description: Retransmisión de Formula 1 en vivo

- Administración y servicios:

    - Portainer:
        icon: portainer.png
        href: http://10.1.6.130:9000
        description: Administración Docker

    - PiHole:
        icon: https://upload.wikimedia.org/wikipedia/commons/0/00/Pi-hole_Logo.png
        href: http://10.1.6.130:7300/admin
        description: Bloqueo de anuncios y rastreadores

- Apps:

    - Mealie:
        icon: mealie.png
        href: http://10.1.6.130:9925
        description: Recetas, menús y lista de la compra

    - Grafana:
        icon: grafana.png
        href: http://10.1.6.130:3000
        description: Plataforma de visualización de datos

    - Stirling PDF:
        icon: https://raw.githubusercontent.com/Stirling-Tools/Stirling-PDF/main/docs/stirling.png
        href: http://10.1.6.130:8080
        description: Herramientas PDF

    - IT Tools:
        icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-catppuccin/main/catppuccin_icons/ittools.png
        href: http://10.1.6.130:8200
        description: Herramientas IT y mas

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://10.1.6.130:7400
        description: Monitorización de servicios

- Estadísticas:

    - CPU:
        widget:
          type: glances
          url: http://10.1.6.130:7500
          metric: cpu

    - Memoria:
        widget:
          type: glances
          url: http://10.1.6.130:7500
          metric: memory

    - Red:
        widget:
          type: glances
          url: http://10.1.6.130:7500
          metric: network:eth0

    - Procesos:
        widget:
          type: glances
          url: http://10.1.6.130:7500
          metric: process

    - Temperatura CPU:
        widget:
          type: glances
          url: http://10.1.6.130:7500
          metric: sensor:cpu_thermal 0

    - Disco I/O:
        widget:
          type: glances
          url: http://10.1.6.130:7500
          metric: disk:mmcblk0


