---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets
- logo:
    icon: https://raw.githubusercontent.com/bait-py/bubiserver/main/image.ico

- resources:
    cpu: true
    disk: /

- openmeteo:
    provider: openmeteo
    label: Sabadell # optional
    latitude: 41.5433
    longitude: 2.1094
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits

- greeting:
    text_size: xl
    text: Bienvenido a BUBI Server

#- datetime:
#    format:
#      timeStyle: short
#      dateStyle: short
