---
version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Spain/Madrid
    ports:
      - 5055:5055
    volumes:
      - /bubiapps/overseerr/config:/app/config
    restart: unless-stopped