version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - /bubiapps/pdf:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - /bubiapps/pdf/config:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false