---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=65533
      - TZ=Europe/Madrid
    volumes:
      - /bubiapps/torrent/config:/config
      - /bubistorage/torrent/downloads:/downloads
      - /bubiapps/torrent/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped